Adds support for passing environment variables that can configure an …
fcrepo-exts/fcrepo-docker pull request #10
Opened 2020-09-22 16:17 UTC by dbernstein

…external database.

Also updates the list of available configuration variables and cleans up the Dockerfile
and README.md

JIRA: https://jira.lyrasis.org/browse/FCREPO-3433

To test: 

```
#  build fcrepo4 
# run the fcrepo-docker build script
./build.sh /path/to/fcrepo.war

# start mysql
docker run --name f6-mysql -e MYSQL_ROOT_PASSWORD=root-pw -e MYSQL_DATABASE=fcrepo -e MYSQL_USER=fcrepo-user -e MYSQL_PASSWORD=fcrepo-pw -p 3306:3306 -d mysql:8.0

# start fedora
docker run -p8080:8080 --name fcrepo-6  -e FCREPO_DB_URL=jdbc:mysql://host.docker.internal:3306/fcrepo -e FCREPO_DB_USERNAME=fcrepo-user -e FCREPO_DB_PASSWORD=fcrepo-pw fcrepo/fcrepo:latest
```
Verify that http://localhost:8080/fcrepo/rest is functioning.

2020-10-01 14:57 UTC, tomcbe approved these changes

2020-10-01 14:57 UTC, tomcbe commented on tomcat/bin/setenv.sh
> --Dfcrepo.ocfl.work.dir=$FCREPO_OCFL_WORK_DIR \
Does Fedora work, when the ocfl directories are not specified explicitly?

2020-10-01 14:57 UTC, tomcbe commented on tomcat/bin/setenv.sh
> --Dfcrepo.ocfl.work.dir=$FCREPO_OCFL_WORK_DIR \
I just saw, that there is a default set in the docker file.

2020-10-01 17:34 UTC, awoods requested changes
Running the start-up commands in the description of the PR results in:
```
Caused by: java.lang.RuntimeException: java.sql.SQLException: An attempt by a client to checkout a Connection has timed out.
```

When I try with postgreSQL, I get a "driver not found" exception.

2020-10-02 08:16 UTC, tomcbe commented
Thanks for double checking @awoods. I don't get any errors, but the mysql database stays empty even when I create new objects.

2020-10-05 23:28 UTC, dbernstein commented
I tried both mysql and postgres successfully and verified that the data was landing in the database.

2020-10-07 15:00 UTC, pwinckles approved these changes
Noting that in the future we should try to move away from environment variable proliferation

2020-10-07 15:04 UTC, awoods approved these changes

2020-10-07 15:04 UTC, merged